# Generated by Django 4.1 on 2022-09-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(max_length=155)),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_plato', models.CharField(choices=[('Entrada', 'Entrada'), ('Plato Principal', 'Plato Principal'), ('Postre', 'Postre'), ('Bebida', 'Bebida'), ('Otro', 'Otro')], max_length=50)),
            ],
        ),
    ]
