# Generated by Django 4.1 on 2022-09-24 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_menu_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mesa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('observacion', models.TextField(blank=True, max_length=255, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.mesas')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.menu')),
            ],
        ),
    ]
