# Generated by Django 4.1 on 2022-09-25 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_usuario'),
        ('paginas', '0003_mesas_orden'),
    ]

    operations = [
    ]
