# Generated by Django 4.1 on 2022-09-28 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenmesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ordenplato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.mesas')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.ordenmesa')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.menu')),
            ],
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
