# Generated by Django 4.1 on 2022-09-28 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_ordenmesa_ordenplato_delete_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmesa',
            name='mesa',
            field=models.ForeignKey(default=20.09, on_delete=django.db.models.deletion.CASCADE, to='paginas.mesas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenmesa',
            name='platos',
            field=models.ManyToManyField(through='paginas.Ordenplato', to='paginas.menu'),
        ),
        migrations.AlterField(
            model_name='ordenmesa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
