# Generated by Django 4.1 on 2022-09-28 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_ordenmesa_mesa_ordenmesa_platos_alter_ordenmesa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmesa',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
