# Generated by Django 4.1 on 2022-09-30 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0010_alter_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Cargo',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Cocinero', 'Cocinero'), ('Mesero', 'Mesero')], max_length=13),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Cocina', 'Cocina'), ('Bebidas', 'Bebidas'), ('Mesero', 'Mesero')], max_length=13),
        ),
        migrations.CreateModel(
            name='Ordenmesas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('observacion', models.TextField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.menu')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginas.mesas')),
            ],
        ),
    ]
