# Generated by Django 4.1 on 2022-09-30 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0011_alter_usuario_cargo_alter_usuario_rol_ordenmesas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenmesa',
            name='platos',
        ),
    ]
