# Generated by Django 4.1 on 2022-09-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0012_remove_ordenmesa_platos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmesa',
            name='platos',
            field=models.ManyToManyField(through='paginas.Ordenplato', to='paginas.menu'),
        ),
    ]
