# Generated by Django 4.1 on 2022-09-30 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0013_ordenmesa_platos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmesas',
            name='orden',
            field=models.ForeignKey(default=2.0, on_delete=django.db.models.deletion.CASCADE, to='paginas.ordenmesa'),
            preserve_default=False,
        ),
    ]
