# Generated by Django 4.1 on 2022-09-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0017_alter_ordenmesas_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenmesas',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
