# Generated by Django 4.1 on 2022-10-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0018_alter_ordenmesas_observacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordenmesa',
            new_name='IdOrden',
        ),
        migrations.DeleteModel(
            name='Ordenplato',
        ),
    ]
